apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mansoori-todo.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | b64enc | quote }}
  {{- if .Values.database.useNeon }}
  DATABASE_URL: {{ .Values.database.neonUrl | b64enc | quote }}
  {{- end }}
